### ISSUE TITLE
couldn't read src/../dist/index.html

### ISSUE THREAD

**Issue by sandiks** [ShashankaNataraj/Juggernaut#1]
error: couldn't read src/../dist/index.html: No such file or directory (os error 2)
  --> src/main.rs:38:32
   |
38 |         .content(Content::Html(include_str!("../dist/index.html")))
   |

**Comment by Exegetech** [comment]
You have to run `npm run watch-webpack` first

**Comment by ShashankaNataraj** [comment]
> error: couldn't read src/../dist/index.html: No such file or directory (os error 2)
> --> src/main.rs:38:32
> |
> 38 | .content(Content::Html(include_str!("../dist/index.html")))
> |

Please note that the editor is in early alpha as of now. I've hardcoded the initial starting directory at: https://github.com/ShashankaNataraj/Juggernaut/blob/master/src/web/app.js#L19 . You might want to change this before starting the editor.

@christiansakai Thanks for replying to the question! Would appreciate any and all help in writing this editor!

**Comment by Exegetech** [comment]
@ShashankaNataraj this is really awesome work! I am primarily a JS developer but recently started Rust I am not that advanced in Rust but I can do stuff around. I'd love to help contributing. ~Any idea where to start digging this up in the code base?~ Any list of features/roadmap?

**Comment by ShashankaNataraj** [comment]
@christiansakai Here you go: https://github.com/ShashankaNataraj/Juggernaut/projects. This project could use help in both the JS and Rust portions, whichever you're comfortable with!

**Comment by Exegetech** [comment]
@ShashankaNataraj Awesome. Right now maybe it is good to wait until you clean up the code structure and introduce basic features. That would help a lot for people who wants to contribute

**Comment by ShashankaNataraj** [comment]
@christiansakai Aye captain! Code cleanup is coming.

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4KYPHCf2n2vhFLW282B6CxYc7EIoDceCldAzbDQneTMefHD-h6g" />

**Comment by rrandom** [comment]
Hi, I am on windows and can't run the code, seems that the packaged js code with spread operator is not supported by  IE

**Comment by ShashankaNataraj** [comment]
@rrandom Thanks for reporting the bug, In our webpack config, we need to transpile the ES6 code into ES5. I currently do not have access to a windows machine.

Any PRs would be much appreciated.

**Comment by Exegetech** [comment]
@rrandom the webpack is using babel 7, here it is to configure it using IE https://babeljs.io/docs/en/babel-preset-env#targets

**Comment by ShashankaNataraj** [comment]
@christiansakai @rrandom I've added a fix for this in: 
https://github.com/ShashankaNataraj/Juggernaut/commit/b7453e3bff0c661ea01533489e7f2c2b97dee889

Can you please check now? I dont see any spread operators in the compressed file, so hoping this fix works for you.

You can do : https://github.com/ShashankaNataraj/Juggernaut#build-from-source

**Comment by rrandom** [comment]
@ShashankaNataraj It works! thanks for the quick fix

**Comment by ShashankaNataraj** [comment]
@rrandom No problemo ! Thanks for raising this issue!

Youll need to open a dir as a project before starting to edit files. Please go through:
https://github.com/ShashankaNataraj/Juggernaut/wiki/FAQ's

**Comment by Exegetech** [comment]
@ShashankaNataraj  Off topic, but if we think that webpack is too complicated for our use case, we can use parcel https://parceljs.org/

**Comment by ShashankaNataraj** [comment]
@christiansakai Thanks for the suggestion, Ive looked at parcel before, but I see that It has some issues with generating a single bundled file: https://github.com/parcel-bundler/parcel/issues/1704

Generating a single file is of utmost importance in the current approach because juggernaut currently reads only one startup html file containing everything: https://github.com/ShashankaNataraj/Juggernaut/blob/master/src/main.rs#L34

Currently the `index.html` file includes Ace from a CDN, I intend to change that very soon. And any hits to the disk after the initial html is loaded is only for files the user wants to read / write.

As a side note, sometimes I think having the files served over HTTP through a random port does give a lot of flexibility in terms of development and tooling instead of this single file approach to loading everything..

**Comment by Exegetech** [comment]
@ShashankaNataraj Ah okay. Yeah in that case just use Webpack. Webpack is good enough for a lot of use cases and very flexible.

**Comment by Exegetech** [comment]
@ShashankaNataraj Just discovered that Parcel support Rust extension compiled to WASM https://parceljs.org/rust.html

**Comment by ShashankaNataraj** [comment]
@christiansakai Yes it does! I was exploring parcel for my resume(https://bitly.com/shashankas-resume) a few days back when I found the rust part of the documentation.

But AFAIK the code that runs in WASM will not be able to access the file system, right?

**Comment by Exegetech** [comment]
If I am not mistaken no it cannot access the file system, so we do still have to use JS.
